package com.nikozka.app.entity;

import com.nikozka.app.dtos.TaskStatus;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;

@Entity
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "tasks")
public class TaskEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "description")
    private String description;
    @Column(name = "date")
    private LocalDate date; // todo make autogenerated in DB

    @Column(name = "status")
    private TaskStatus status;
    @Column(name = "user_id")
    private Long userId;
}
